# Generated by Django 5.2.1 on 2025-05-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebleriap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=200)),
                ('Metodo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sucursale',
            fields=[
                ('ID_Sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Sucursal', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=15)),
                ('Horario', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('ID_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Empleado', models.CharField(max_length=100)),
                ('Puesto', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Sucursal_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muebleriap.sucursale')),
            ],
        ),
    ]
