# Generated by Django 5.2.1 on 2025-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebleriap', '0002_cliente_sucursale_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Material',
            field=models.CharField(default='Sin especificar', max_length=50),
            preserve_default=False,
        ),
    ]
